version: 2

sources:
  - name: gainsight
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: gainsight
    loader: Airflow
    loaded_at_field: to_timestamp(_updated_at::NUMBER)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      error_after: {count: 24, period: hour}

    tables:
    - name: gainsight_instance_info