version: 2

models:
  - name: marketing_site_merge_requests_files
    description: This table contains each marketing site file changed per merge request on its own line.
    columns:
    - name: marketing_file_edited
    - name: merge_request_version_diffs
    - name: plain_diff_url_path
    - name: source_branch_name
