version: 2

models:
    - name: version_usage_data_month
      description: usage ping data values aggregated by month for each UUID.
      columns:
          - name: created_at
            tests:
                - not_null
          - name: unique_key
            tests:
                - not_null
          - name: uuid
            tests:
                - not_null
          - name: edition
            description: Indicates CE or EE with some additional granularity. Current values are EE, EE Free, EEU, EEP, and EES. Not sure what those mean this should be updated to add that.
          - name: edition_type
            description: The tier. Current values are CE, Premium, Ultimate, Starter, Core.
          - name: main_edition
            description: Either EE or CE.
