version: 2

models:
    - name: snowplow_gitlab_staging_events
      description: '{{ doc("snowplow_gitlab_staging_events") }}'
      columns:
          - name: uploaded_at
            tests:
                - not_null


    - name: snowplow_staging_unnested_events
      description: This is the primary events table which is the union of the Fishtown and GitLab tables. All of the unstructured events are unpacked - [link click tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#39-link-click-tracking), [form tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#3101-enableformtracking), and [time tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#timing).
      columns:
          - name: uploaded_at
            tests:
                - not_null
