version: 2

sources:
  - name: discourse
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: discourse
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
    - name: accepted_solutions
    - name: consolidated_page_views
    - name: daily_engaged_users
    - name: page_view_total_reqs
    - name: posts
    - name: signups
    - name: time_to_first_response
    - name: topics_with_no_response
    - name: visits

