version: 2

models:
  - name: gcp_billing_export_source
    description: Base model for gcp billing export
    columns:
      - name: primary_key
        tests:
          - not_null
      - name: billing_account_id
        tests:
          - not_null
