version: 2

models:
  - name: customers_db_trials
    description: '{{ doc("customers_db_trials") }}'
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: latest_trial_per_namespace_xf
    description: '{{ doc("latest_trial_per_namespace_xf") }}'
    columns:
      - name: namespace_id
        tests:
          - not_null
          - unique

  - name: customers_db_trial_histories
    description: '{{ doc("customers_db_trial_histories") }}'
    columns:
      - name: gl_namespace_id
      - name: start_date
      - name: expired_on
      - name: created_at
      - name: updated_at
      - name: glm_source
      - name: glm_content
      - name: trial_entity
