version: 2

models:
    - name: discourse_accepted_solutions
      description: 'Pre-formatted report data displaying the accepted reporting values on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_consolidated_page_views
      description: 'Pre-formatted report data based on the number of page views on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: request_type
          - name: request_label
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null


    - name: discourse_daily_engaged_users
      description: 'Pre-formatted report data based on the number of daily engaged users on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_page_view_total_reqs
      description: 'Pre-formatted report data based on the number of total page view requests the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_posts
      description: 'Pre-formatted report data based on the number of posts on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_signups
      description: 'Pre-formatted report data based on the number of signups on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_time_to_first_response
      description: 'Pre-formatted report data downloaded from the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_topics_with_no_response
      description: 'Pre-formatted report data downloaded from the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: discourse_visits
      description: 'Pre-formatted report data based on the number of visits on the gitlab.com discourse instance. Used in calculation of Ticket deflection KPI'
      columns:
          - name: report_start_date
            tags: ["discourse", "social"]
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null
