version: 2

sources:
  - name: marketo
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: marketo
    loader: fivetran
    loaded_at_field: _FIVETRAN_SYNCED

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 36, period: hour}

    tables:
      - name: activity_add_to_list
      - name: activity_add_to_nurture
      - name: activity_add_to_sfdc_campaign
      - name: activity_add_to_opportunity
      - name: activity_call_webhook
      - name: activity_change_data_value
      - name: activity_change_nurture_cadence
      - name: activity_change_nurture_track
      - name: activity_change_owner
      - name: activity_change_score
      - name: activity_change_segment
      - name: activity_change_status_in_progression
      - name: activity_change_status_in_sfdc_campaign
        freshness: null
      - name: activity_click_email
      - name: activity_click_link
      - name: activity_convert_lead
        freshness: null
      - name: activity_delete_lead
        freshness: null
      - name: activity_email_bounced
      - name: activity_email_bounced_soft
      - name: activity_email_delivered
      - name: activity_execute_campaign
      - name: activity_fill_out_form
      - name: activity_fill_out_linkedin_lead_gen_form
      - name: activity_interesting_moment
      - name: activity_merge_leads
      - name: activity_new_lead
      - name: activity_open_email
      - name: activity_push_lead_to_marketo
      - name: activity_remove_from_list
      - name: activity_remove_from_sfdc_campaign
        freshness: null
      - name: activity_request_campaign
      - name: activity_send_alert
      - name: activity_send_email
      - name: activity_sfdc_activity
      - name: activity_sfdc_activity_updated
      - name: activity_sync_lead_to_sfdc
      - name: activity_type
      - name: activity_unsubscribe_email
      - name: activity_update_opportunity
      - name: activity_visit_webpage
      - name: lead