version: 2

models:
  - name: zuora_revenue_accounting_type_source
    description: '{{ doc("zuora_revenue_accounting_type_source") }}'
    columns:
      - name: accounting_type_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_approval_detail_source
    description: '{{ doc("zuora_revenue_approval_detail_source") }}'
    columns:
      - name: primary_key
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_book_source
    description: '{{ doc("zuora_revenue_book_source") }}'
    columns:
      - name: book_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_calendar_source
    description: '{{ doc("zuora_revenue_calendar_source") }}'
    columns:
      - name: period_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_manual_journal_entry_source
    description: '{{ doc("zuora_revenue_manual_journal_entry_source") }}'
    columns: 
      - name: manual_journal_entry_line_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_organization_source
    description: '{{ doc("zuora_revenue_organization_source") }}'
    columns:
      - name: organization_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_bill_source
    description: '{{ doc("zuora_revenue_revenue_contract_bill_source") }}'
    columns:
      - name: revenue_contract_bill_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_header_source
    description: '{{ doc("zuora_revenue_revenue_contract_header_source") }}'
    columns:
      - name: revenue_contract_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_hold_source
    description: '{{ doc("zuora_revenue_revenue_contract_hold_source") }}'
    columns:
      - name: revenue_contract_hold_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_line_source
    description: '{{ doc("zuora_revenue_revenue_contract_line_source") }}'
    columns:
      - name: revenue_contract_line_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_performance_obligation_source
    description: '{{ doc("zuora_revenue_revenue_contract_performance_obligation_source") }}'
    columns:
      - name: revenue_contract_performance_obligation_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_schedule_source
    description: '{{ doc("zuora_revenue_revenue_contract_schedule_source") }}'
    columns:
      - name: primary_key
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_revenue_contract_schedule_deleted_source
    description: '{{ doc("zuora_revenue_revenue_contract_schedule_deleted_source") }}'
    columns:
      - name: revenue_contract_schedule_id
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null
  - name: zuora_revenue_waterfall_source
    description: '{{ doc("zuora_revenue_waterfall_source") }}'
    columns:
      - name: primary_key
        tags: ["tdf","zuora"]
        tests:
          - unique
          - not_null