version: 2

sources:
  - name: zuora_revenue
    tags: ["tdf","zuora_revenue"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: zuora_revenue
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: zuora_revenue_accounting_type
        identifier: bi3_acct_type
        description: '{{ doc("zuora_revenue_accounting_type_source") }}'
      - name: zuora_revenue_approval_detail
        identifier: bi3_appr_dtl
        description: '{{ doc("zuora_revenue_approval_detail_source") }}'
      - name: zuora_revenue_book
        identifier: bi3_book
        description: '{{ doc("zuora_revenue_book_source") }}'
      - name: zuora_revenue_calendar
        identifier: bi3_calendar
        description: '{{ doc("zuora_revenue_calendar_source") }}'
      - name: zuora_revenue_manual_journal_entry
        identifier: bi3_mje
        description: '{{ doc("zuora_revenue_manual_journal_entry_source") }}'
      - name: zuora_revenue_organization
        identifier: bi3_org
        description: '{{ doc("zuora_revenue_organization_source") }}'
      - name: zuora_revenue_revenue_contract_bill
        identifier: bi3_rc_bill
        description: '{{ doc("zuora_revenue_revenue_contract_bill_source") }}'
      - name: zuora_revenue_revenue_contract_header
        identifier: bi3_rc_head
        description: '{{ doc("zuora_revenue_revenue_contract_header_source") }}'
      - name: zuora_revenue_revenue_contract_hold
        identifier: bi3_rc_hold
        description: '{{ doc("zuora_revenue_revenue_contract_hold_source") }}'
      - name: zuora_revenue_revenue_contract_line
        identifier: bi3_rc_lns
        description: '{{ doc("zuora_revenue_revenue_contract_line_source") }}'
      - name: zuora_revenue_revenue_contract_performance_obligation
        identifier: bi3_rc_pob
        description: '{{ doc("zuora_revenue_revenue_contract_performance_obligation_source") }}'
      - name: zuora_revenue_revenue_contract_schedule
        identifier: bi3_rc_schd
        description: '{{ doc("zuora_revenue_revenue_contract_schedule_source") }}'
      - name: zuora_revenue_revenue_contract_schedule_deleted
        identifier: bi3_rc_schd_del
        description: '{{ doc("zuora_revenue_revenue_contract_schedule_deleted_source") }}'
      - name: zuora_revenue_waterfall_summary
        identifier: bi3_wf_summ
        description: '{{ doc("zuora_revenue_waterfall_source") }}'
      - name: zuora_revenue_invoice_accounting_summary
        identifier: bi3_ri_acct_summ