version: 2

models:
  - name: rpt_security_marketing_update_frequency_monthly
    description: This is a dbt model (view) of total count of Marketing MR file changes for Security division.
    columns:
    - name: month_merged_at
      tests:
        - not_null
    - name: mr_count_security
      tests:
        - not_null
