version: 2

sources:
  - name: xactly
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_xactly
    loader: Stitch
    loaded_at_field: __loaded_at

    quoting:
      database: true
      schema: false
      identifier: false
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 36, period: hour}

    tables:
      - name: xc_attainment_measure
      - name: xc_attainment_measure_criteria
      - name: xc_credit
      - name: xc_credit_adjustment
        freshness: null
      - name: xc_credit_held
        freshness: null
      - name: xc_credit_totals
        freshness: null
      - name: xc_credit_type
      - name: xc_position
      - name: xc_position_hist
      - name: xc_pos_hierarchy
      - name: xc_pos_hierarchy_hist
      - name: xc_pos_hierarchy_type
      - name: xc_pos_hierarchy_type_hist
      - name: xc_pos_part_assignment
      - name: xc_pos_part_assignment_hist
      - name: xc_pos_relations
      - name: xc_pos_relations_hist
      - name: xc_pos_rel_type
      - name: xc_pos_rel_type_hist
      - name: xc_pos_title_assignment
      - name: xc_pos_title_assignment_hist
      - name: xc_quota_assignment
      - name: xc_quota_assignment_hist
      - name: xc_quota
      - name: xc_quota_hist
      - name: xc_quota_relationship
        freshness: null
      - name: xc_quota_totals
        freshness: null
      - name: xc_role
      - name: xc_participant
      - name: xc_period
      - name: xc_period_type
      - name: xc_plan
      - name: xc_plan_assignment
      - name: xc_user 
      - name: xc_comp_order_item
      - name: xc_comp_order_item_detail
        freshness: null
