with
    source as (select * from {{ source("xactly", "xc_comp_order_item") }}),

    renamed as (

        select

            comp_order_item_id::float as comp_order_item_id,
            version::float as version,
            is_active::varchar as is_active,
            item_code::varchar as item_code,
            line_number::float as line_number,
            amount::float as amount,
            amount_unit_type_id::float as amount_unit_type_id,
            amount_pct::float as amount_pct,
            incentive_date::varchar as incentive_date,
            period_id::float as period_id,
            order_date::varchar as order_date,
            source_id::float as source_id,
            order_type_id::float as order_type_id,
            is_processed::varchar as is_processed,
            discount::float as discount,
            quantity::float as quantity,
            product_id::float as product_id,
            product_name::varchar as product_name,
            customer_id::float as customer_id,
            customer_name::varchar as customer_name,
            geography_id::float as geography_id,
            geography_name::varchar as geography_name,
            upload_id::float as upload_id,
            batch_number::float as batch_number,
            batch_id::float as batch_id,
            batch_name::varchar as batch_name,
            related_order_code::varchar as related_order_codes,
            related_item_code::varchar as related_item_code,
            related_item_id::float as related_item_id,
            order_code::varchar as order_code,
            descr::varchar as descr,
            item_status::varchar as item_status,
            status_date::varchar as status_date,
            splt_amt_pct_total::float as splt_amt_pct_total,
            invoice__date::varchar as invoice_date,
            subscription__start__date::varchar as subscription_start_date,
            subscription__end__date::varchar as subscription_end_date,
            stage::varchar as stage,
            opportunity__name::varchar as opportunity_name,
            invoice__entity::varchar as invoice_entity,
            invoice__number::varchar as invoice_number,
            prevent__rolling::varchar as prevent_rolling,
            partner__deal__type::varchar as partner_deal_type,
            partner__engagement::varchar as partner_engagement,
            account__territory::varchar as account_territory,
            product__category::varchar as product_category,
            sdr__assigned__role::varchar as sdr_assigned_role,
            initial__source::varchar as initial_source,
            order__subtype::varchar as order_subtype,
            region::varchar as region,
            user__segment::varchar as user_segment,
            account__owner__team::varchar as account_owner_team,
            sa__team::varchar as sa_team,
            initiative::varchar as initiative,
            outreach__meeting__type::varchar as outreach_meeting_type,
            event__disposition::varchar as event_disposition,
            subject::varchar as subject,
            iqm__submitted_by__role::varchar as iqm_submitted_by_role,
            created__by__team::varchar as created_by_team,
            new__logo__target__account::varchar as new_logo_target_account,
            deal__path::varchar as deal_path,
            dr__partner::varchar as dr_partner,
            bhr_eeid::varchar as bhr_eeid,
            sqs::varchar as sqs,
            resale__partner::varchar as resale_partner,
            type::varchar as type,
            type__name::varchar as type_name,
            is__sao::varchar as is_sao,
            web__portal__purchase::varchar as web_portal_purchase,
            stamped__opp__owner__user__region::varchar as stamped_opp_owner_user_region,
            opportunity__category::varchar as opportunity_category,
            split__partner__type::varchar as split_partner_type,
            partner__sourced__employee__id::varchar as partner_sourced_employee_id,
            partner__co_sell__employee__id::varchar as partner_cosell_employee_id,
            invoice__amount::float as invoice_amount,
            channel__neutral__amount::float as channel_neutral_amount,
            arr__net__amount::float as arr_net_amount,
            arr__growth__amount::float as arr_growth_amount,
            true__up__amount::float as true_up_amount,
            arr__gross__amount::float as arr_gross_amount,
            pio__amount::float as pio_amount,
            arr_y2_plus__amount::float as arr_y2plus_amount,
            professional__services__amount::float as professional_services_amount,
            opportunity__term::float as opportunity_term,
            partner__discount::float as partner_discount,
            calculated__discount::float as calculated_discount,
            channel__neutral__y2_plus__amount::float as channel_neutral_y2plus_amount,
            recurring__amount::float as recurring_amount,
            non__recurring__amount::float as non_recurring_amount,
            commission__adj::float as commission_adj,
            stub__iacv::float as stub_iacv,
            guarantee__adj::float as guarantee_adj,
            arr__basis::float as arr_basis,
            won__arr__basis::float as won_arr_basis,
            lam__dev__count::float as lam_dev_count,
            arr__basis__clari::float as arr_basis_clari,
            channel__split__percentage::float as channel_split_percentage,
            invoice__amount__unit_type_id::float as invoice_amount_unittypeid,
            channel__neutral__amount__unit_type_id::float
            as channel_neutral_amount_unittypeid,
            arr__net__amount__unit_type_id::float as arr_net_amount_unittypeid,
            arr__growth__amount__unit_type_id::float as arr_growth_amount_unittypeid,
            true__up__amount__unit_type_id::float as true_up_amount_unittypeid,
            arr__gross__amount__unit_type_id::float as arr_gross_amount_unittypeid,
            pio__amount__unit_type_id::float as pio_amount_unittypeid,
            arr_y2_plus__amount__unit_type_id::float as arr_y2plus_amount_unittypeid,
            professional__services__amount__unit_type_id::float
            as professional_services_amount_unittypeid,
            opportunity__term__unit_type_id::float as opportunity_term_unittypeid,
            partner__discount__unit_type_id::float as partner_discount_unittypeid,
            calculated__discount__unit_type_id::float as calculated_discount_unittypeid,
            channel__neutral__y2_plus__amount__unit_type_id::float
            as channel_neutral_y2plus_amount_unittypeid,
            recurring__amount__unit_type_id::float as recurring_amount_unittypeid,
            non__recurring__amount__unit_type_id::float
            as non_recurring_amount_unittypeid,
            commission__adj__unit_type_id::float as commission_adj_unittypeid,
            stub__iacv__unit_type_id::float as stub_iacv_unittypeid,
            guarantee__adj__unit_type_id::float as guarantee_adj_unittypeid,
            arr__basis__unit_type_id::float as arr_basis_unittypeid,
            won__arr__basis__unit_type_id::float as won_arr_basis_unittypeid,
            lam__dev__count__unit_type_id::float as lam_dev_count_unittypeid,
            arr__basis__clari__unit_type_id::float as arr_basis_clari_unittypeid,
            channel__split__percentage__unit_type_id::float
            as channel_split_percentage_unittypeid,
            created_date::varchar as created_date,
            created_by_id::float as created_by_id,
            created_by_name::varchar as created_by_name,
            modified_date::varchar as modified_date,
            modified_by_id::float as modified_by_id,
            modified_by_name::varchar as modified_by_name

        from source

    )

select *
from renamed
