with
    source as (select * from {{ source("xactly", "xc_credit") }}),
    renamed as (

        select

            amount::float as amount,
            amount_display_symbol::varchar as amount_display_symbol,
            amount_unit_type_id::float as amount_unit_type_id,
            batch_number::float as batch_number,
            business_group_id::float as business_group_id,
            created_by_id::float as created_by_id,
            created_by_name::varchar as created_by_name,
            created_date::varchar as created_date,
            credit_id::float as credit_id,
            credit_type_id::float as credit_type_id,
            credit_type_name::varchar as credit_type_name,
            customer_id::float as customer_id,
            customer_name::varchar as customer_name,
            eff_participant_id::float as eff_participant_id,
            eff_position_id::float as eff_position_id,
            estimated_rel_date::varchar as estimated_rel_date,
            ever_on_hold::varchar as ever_on_hold,
            geography_id::float as geography_id,
            geography_name::varchar as geography_name,
            incentive_date::varchar as incentive_date,
            is_active::varchar as is_active,
            is_held::varchar as is_held,
            is_processed::varchar as is_processed,
            is_rollable::varchar as is_rollable,
            item_code::varchar as item_code,
            mgr_eff_part_id::float as mgr_eff_part_id,
            mgr_eff_pos_id::float as mgr_eff_pos_id,
            mgr_master_pos_id::float as mgr_master_pos_id,
            modified_by_id::float as modified_by_id,
            modified_by_name::varchar as modified_by_name,
            modified_date::varchar as modified_date,
            name::varchar as name,
            order_code::varchar as order_code,
            order_item_id::float as order_item_id,
            participant_id::float as participant_id,
            participant_name::varchar as participant_name,
            period_id::float as period_id,
            period_name::varchar as period_name,
            plan_id::float as plan_id,
            plan_name::varchar as plan_name,
            position_id::float as position_id,
            position_name::varchar as position_name,
            product_id::float as product_id,
            product_name::varchar as product_name,
            reason_code_id::float as reason_code_id,
            reason_code_name::varchar as reason_code_name,
            release_date::varchar as release_date,
            release_group_id::float as release_group_id,
            rollable_on_reporting::varchar as rollable_on_reporting,
            rule_id::float as rule_id,
            rule_name::varchar as rule_name,
            run_id::float as run_id,
            source_credit_id::float as source_credit_id,
            source_position_id::float as source_position_id,
            src_pos_relation_type_id::float as src_pos_relation_type_id,
            sub_batch_number::float as sub_batch_number,
            sub_part_key::varchar as sub_part_key,
            trans_id::float as trans_id

        from source

    )

select *
from renamed
