version: 2

models:
    - name: mart_monthly_counter_adoption
      description: '{{ doc("mart_monthly_counter_adoption") }}'
      tests:
      - unique:
          column_name: "concat(reporting_month, metrics_path, edition)"
      columns:
          - name: reporting_month
            tests:
              - not_null
          - name: metrics_path
            tests:
              - not_null
          - name: edition
            tests:
              - not_null
