version: 2

sources:
  - name: thanos
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: PROMETHEUS
    loader: snowflake_task
    loaded_at_field: UPLOADED_AT

    quoting:
      database: true
      schema: false
      identifier: false

    freshness: 
      warn_after: {count: 24, period: hour}
      error_after: {count: 36, period: hour}

    tables:
      - name: periodic_queries
        description: thanos_periodic_queries