{{ config(tags=["mnpi"]) }}

with
    source as (select * from {{ source("salesforce", "zqu_quote") }}),
    renamed as (

        select
            id::varchar as zqu_quote_id,
            quote_id_18__c::varchar as quote_id_18,
            quote_id__c::varchar as quote_id,
            account_id__c::varchar as account_id,
            opportunity_id__c::varchar as opportunity_id,

            invoice_number__c::varchar as invoice_number,
            admin_primary_backfill__c::boolean as admin_primary_backfill,
            approval_stage_fmt__c::varchar as approval_stage_fmt,
            approval_stage__c::varchar as approval_stage,
            asm__c::varchar as asm,
            bill_to_address_1__c::varchar as bill_to_address_1,
            bill_to_address_2__c::varchar as bill_to_address_2,
            bill_to_contact_updated__c::boolean as bill_to_contact_updated,
            bill_to_country__c::varchar as bill_to_country,
            bill_to_email_address__c::varchar as bill_to_email_address,
            bill_to_phone__c::varchar as bill_to_phone,
            calculated_discount__c::float as calculated_discount,
            charge_summary_sub_total__c::float as charge_summary_sub_total,
            click_through_eula_contract_language__c::varchar
            as click_through_eula_contract_language,
            delta_arr__c::float as delta_arr,
            distributor__c::varchar as distributor,
            gitlab_privacy_url__c::varchar as gitlab_privacy_url,
            has_githost_cb__c::boolean as has_githost_cb,
            has_invoice_owner__c::float as has_invoice_owner,
            invoice_paid__c::boolean as invoice_paid,
            key_assumptions__c::varchar as key_assumptions,
            mailing_street__c::varchar as mailing_street,
            name::varchar as zqu_quote_name,
            nrv_roll_up__c::float as nrv_roll_up,
            opportunity_amount__c::float as opportunity_amount,
            opportunity_stage__c::varchar as opportunity_stage,
            quote_amendment_last_modified_date__c::timestamp_tz
            as quote_amendment_last_modified_date,
            quote_opportunity_amount_match__c::varchar
            as quote_opportunity_amount_match,
            quote_rateplan_last_updated_time__c::timestamp_tz
            as quote_rateplan_last_updated_time,
            ra_use_primary_quote__c::boolean as ra_use_primary_quote,
            required_approvals_from_vp_of_sales_rd__c::varchar
            as required_approvals_from_vp_of_sales_rd,
            resellerbilltostateprovince__c::varchar as reseller_bill_to_state_province,
            bill_to_country_code__c::varchar as bill_to_country_code,
            bill_to_postal_code__c::varchar as bill_to_postal_code,
            clickthrougheularequired__c::varchar as click_through_eula_required,
            createdbyfirstname__c::varchar as created_by_first_name,
            invoice_owner_account_type__c::varchar as invoice_owner_account_type,
            invoice_owner_vat_id__c::varchar as invoice_owner_vat_id,
            invoice_paid_date__c::timestamp_tz as invoice_paid_date,
            max_premium_discount_2__c::float as max_premium_discount_2,
            mrr_rollup__c::float as mrr_rollup,
            partner_registered__c::varchar as partner_registered,
            professional_services_amount__c::float as professional_services_amount,
            bill_to_city__c::varchar as bill_to_city,
            bill_to_contact_info_updated__c::varchar as bill_to_contact_info_updated,
            bill_to_initial_source__c::varchar as bill_to_initial_source,
            bill_to_street__c::varchar as bill_to_street,
            count_of_rate_plans__c::float as count_of_rate_plans,
            createddate::timestamp_tz as created_date,
            entity_bank_information__c::varchar as entity_bank_information,
            invoiceownerpaymentterms__c::float as invoice_owner_payment_terms,
            license_amount_v2__c::float as license_amount_v2,
            partner_assisted__c::varchar as partner_assisted,
            previous_renewal_term__c::float as previous_renewal_term,
            quote_end_date__c::timestamp_tz as quote_end_date,
            quote_entity_beneficiary_information__c::varchar
            as quote_entity_beneficiary_information,
            quote_entity_legal_name__c::varchar as quote_entity_legal_name,
            resellerbilltocity__c::varchar as reseller_bill_to_city,
            bill_to_name__c::varchar as bill_to_name,
            bill_to_state__c::varchar as bill_to_state,
            change_sold_to_contact__c::varchar as change_sold_to_contact,
            createdbyemailaddress__c::varchar as created_by_email_address,
            entity_contact_information__c::varchar as entity_contact_information,
            has_githost__c::float as has_githost,
            invoice_amount__c::float as invoice_amount,
            new_sub_on_addon_renewal_approved__c::boolean
            as new_sub_on_addon_renewal_approved,
            non_standard_contract_terms__c::varchar as non_standard_contract_terms,
            ownerid::varchar as owner_id,
            partner_fulfillment__c::varchar as partner_fulfillment,
            po_required__c::boolean as po_required,
            professional_services_description__c::varchar
            as professional_services_description,
            pub_sec_owner__c::varchar as pub_sec_owner,
            quote_amendment_count__c::float as quote_amendment_count,
            quote_entity_contact_information__c::varchar
            as quote_entity_contact_information,
            rate_plans__c::varchar as rate_plans,
            rd__c::varchar as rd,
            recordtypeid::varchar as record_type_id,
            required_approvals_from_asm__c::varchar as required_approvals_from_asm,
            invoice_owner_country__c::varchar as invoice_owner_country,
            purchase_order__c::varchar as purchase_order,
            required_approvals_from_ceo__c::varchar as required_approvals_from_ceo,
            entity_beneficiary_information__c::varchar
            as entity_beneficiary_information,
            highest_quote_rate_plan__c::varchar as highest_quote_rate_plan,
            quote_entity_override__c::boolean as quote_entity_override,
            renewal_mrr__c::float as renewal_mrr,
            quote_tcv__c::float as quote_tcv,
            required_approvals_from_cfo__c::varchar as required_approvals_from_cfo,
            required_approvals_from_cs__c::varchar as required_approvals_from_cs,
            required_approvals_from_legal__c::varchar as required_approvals_from_legal,
            required_approvals_from_vp_of_channel__c::varchar
            as required_approvals_from_vp_of_channel,
            requires_deal_desk_review__c::boolean as requires_deal_desk_review,
            resellerbilltocountry__c::varchar as reseller_bill_to_country,
            resellerbilltopostalcode__c::varchar as reseller_bill_to_postal_code,
            resellerbilltostreet__c::varchar as reseller_bill_to_street,
            click_through_eula_test__c::varchar as click_through_eula_test,
            gitlab_terms_url__c::varchar as gitlab_terms_url,
            invoice_owner_account_id__c::varchar as invoice_owner_account_id,
            project_scope__c::varchar as project_scope,
            quote_entity_bank_information__c::varchar as quote_entity_bank_information,
            quote_entity_check_remittance__c::varchar as quote_entity_check_remittance,
            quote_entity__c::varchar as quote_entity,
            required_approvals_from_cro__c::varchar as required_approvals_from_cro,
            resellerbilltoemail__c::varchar as reseller_bill_to_email,
            resellerbilltofirstname__c::varchar as reseller_bill_to_first_name,
            resellerbilltolastname__c::varchar as reseller_bill_to_last_name,
            resellerbilltophone__c::varchar as reseller_bill_to_phone,
            reseller_bill_to__c::varchar as reseller_bill_to,
            license_amount__c::float as license_amount,
            required_approvals_from_rd__c::varchar as required_approvals_from_rd,
            reseller_account_name__c::varchar as reseller_account_name,
            reseller_po_status__c::varchar as reseller_po_status,
            saas_addendum_existing_agreement_lang__c::varchar
            as saas_addendum_existing_agreement_lang,
            send_githost_email_to_support__c::boolean as send_githost_email_to_support,
            sold_to_address_2__c::varchar as sold_to_address_2,
            sold_to_city__c::varchar as sold_to_city,
            sold_to_contact_updated__c::boolean as sold_to_contact_updated,
            sold_to_country_code__c::varchar as sold_to_country_code,
            sold_to_country__c::varchar as sold_to_country,
            sold_to_email_address__c::varchar as sold_to_email_address,
            sold_to_email__c::varchar as sold_to_email,
            sold_to_name__c::varchar as sold_to_name,
            sold_to_phone__c::varchar as sold_to_phone,
            sold_to_state__c::varchar as sold_to_state,
            start_date_vs_close_date__c::float as start_date_vs_close_date,
            submitter_comments__c::varchar as submitter_comments,
            subscription_agreement_effective_date_ca__c::varchar
            as subscription_agreement_effective_date_ca,
            subscription_agreement_effective_date__c::timestamp_tz
            as subscription_agreement_effective_date,
            tax_exempt_checkbox__c::boolean as tax_exempt_checkbox,
            tcv_including_discount__c::float as tcv_including_discount,
            total_partner_discount__c::float as total_partner_discount,
            trigger_workflow__c::boolean as trigger_workflow,
            true_up_amount__c::float as true_up_amount,
            vat_tax_id__c::varchar as vat_tax_id,
            vp_of_sales__c::varchar as vp_of_sales,
            wip_arr_iacv_delta__c::float as wip_arr_iacv_delta,
            x_trigger_quote_approval_check__c::boolean
            as x_trigger_quote_approval_check,
            reseller_type__c::varchar as reseller_type,
            sold_to_address_1__c::varchar as sold_to_address_1,
            sold_to_contact_is_null__c::boolean as sold_to_contact_is_null,
            sold_to_initial_source__c::varchar as sold_to_initial_source,
            sold_to_postal_code__c::varchar as sold_to_postal_code,
            subscription_agreement_id__c::varchar as subscription_agreement_id,
            systemmodstamp::timestamp_tz as system_mod_stamp,
            task_schedule__c::varchar as task_schedule,
            watch_quote__c::boolean as watch_quote,
            sold_to_contact_info_updated__c::varchar as sold_to_contact_info_updated,
            subscription_agreement_amendments__c::varchar
            as subscription_agreement_amendments,
            zqu__account__c::varchar as zqu__account,
            zqu__applycreditbalance__c::boolean as zqu__apply_credit_balance,
            zqu__billingbatch__c::varchar as zqu__billing_batch,
            zqu__billingmethod__c::varchar as zqu__billing_method,
            zqu__billtocontact__c::varchar as zqu__bill_to_contact,
            zqu__cancellationdate__c::timestamp_tz as zqu_cancellation_date,
            zqu__cancellationeffectivedate__c::varchar
            as zqu__cancellation_effective_date,
            zqu__certificate_id__c::varchar as zqu__certificate_id,
            zqu__certificate_type__c::varchar as zqu__certificate_type,
            zqu__company_code__c::varchar as zqu__company_code,
            zqu__currency__c::varchar as zqu__currency,
            zqu__deltatcv__c::float as zqu__delta_tcv,
            zqu__electronicpaymentmethodid__c::varchar
            as zqu__electronic_payment_method_id,
            zqu__existingproductsstored__c::boolean as zqu__existing_products_stored,
            zqu__existsubscriptionid__c::varchar as zqu__exist_subscription_id,
            zqu__generateinvoice__c::boolean as zqu__generate_invoice,
            zqu__hidden_subscription_name__c::varchar as zqu__hidden_subscription_name,
            zqu__initialterm__c::float as zqu__initial_term,
            zqu__invoiceownerid__c::varchar as zqu__invoice_owner_id,
            zqu__invoiceownername__c::varchar as zqu__invoice_owner_name,
            zqu__amendment_name__c::varchar as zqu__amendment_name,
            zqu__approvalstatus__c::varchar as zqu__approval_status,
            zqu__calculate_quote_metrics_through__c::varchar
            as zqu__calculate_quote_metrics_through,
            zqu__communicationprofile__c::varchar as zqu__communication_profile,
            zqu__description__c::varchar as zqu__description,
            zqu__invoiceprocessingoption__c::varchar as zqu__invoice_processing_option,
            zqu__invoiceseparately__c::boolean as zqu__invoice_separately,
            zqu__is_charge_expired__c::boolean as zqu__is_charge_expired,
            zqu__is_parent_quote__c::boolean as zqu__is_parent_quote,
            zqu__mrr__c::float as zqu__mrr,
            zqu__number__c::varchar as zqu__number,
            zqu__paymentgateway__c::varchar as zqu__payment_gateway,
            zqu__paymentmethod__c::varchar as zqu__payment_method,
            zqu__paymentterm__c::varchar as zqu__payment_term,
            zqu__previewed_delta_tcv__c::float as zqu__previewed_delta_tcv,
            zqu__previewed_mrr__c::float as zqu__previewed_mrr,
            zqu__previewed_subtotal__c::float as zqu__previewed_subtotal,
            zqu__primary__c::boolean as zqu__primary,
            zqu__processpayment__c::boolean as zqu__process_payment,
            zqu__quotebusinesstype__c::varchar as zqu__quote_business_type,
            zqu__quotetemplate__c::varchar as zqu__quote_template,
            zqu__recordreadonly__c::boolean as zqu__record_read_only,
            zqu__renewaltermperiodtype__c::varchar as zqu__renewal_term_period_type,
            zqu__soldtocontact__c::varchar as zqu__sold_to_contact,
            zqu__status__c::varchar as zqu__status,
            zqu__subscriptiontermenddate__c::timestamp_tz
            as zqu__subscription_term_end_date,
            zqu__subscriptiontermstartdate__c::timestamp_tz
            as zqu__subscription_term_start_date,
            zqu__subscriptiontype__c::varchar as zqu__subscriptiontype,
            zqu__subscription_name__c::varchar as zqu__subscription_name,
            zqu__subscription_term_type__c::varchar as zqu__subscription_term_type,
            zqu__taxexempteffectivedate__c::timestamp_tz
            as zqu__tax_exempt_effective_date,
            zqu__taxexemptexpirationdate__c::timestamp_tz
            as zqu__tax_exempt_expiration_date,
            zqu__terms__c::varchar as zqu__terms,
            zqu__zuoraentityid__c::varchar as zqu__zuora_entity_id,
            zqu__zuora_account_number__c::varchar as zqu__zuora_account_number,
            zqu__autorenew__c::boolean as zqu__auto_renew,
            zqu__deltamrr__c::float as zqu__delta_mrr,
            zqu__initialtermperiodtype__c::varchar as zqu__initial_term_period_type,
            zqu__invoicetemplate__c::varchar as zqu__invoice_template,
            zqu__issuing_jurisdiction__c::varchar as zqu__issuing_jurisdiction,
            zqu__opportunity__c::varchar as zqu__opportunity,
            zqu__previewed_delta_mrr__c::float as zqu__previewed_delta_mrr,
            zqu__previewed_discount__c::float as zqu__previewed_discount,
            zqu__previewed_tax__c::float as zqu__previewed_tax,
            zqu__previewed_tcv__c::float as zqu__previewed_tcv,
            zqu__previewed_total__c::float as zqu__previewed_total,
            zqu__renewalsetting__c::varchar as zqu__renewal_setting,
            zqu__renewalterm__c::float as zqu__renewal_term,
            zqu__startdate__c::timestamp_tz as zqu__start_date,
            zqu__subscriptionversion__c::float as zqu__subscription_version,
            zqu__tax_exempt_description__c::varchar as zqu__tax_exempt_description,
            zqu__tax_exempt__c::varchar as zqu__tax_exempt,
            zqu__tcv__c::float as zqu__tcv,
            zqu__termstartdate__c::timestamp_tz as zqu__term_start_date,
            zqu__total__c::float as zqu__total,
            zqu__validuntil__c::timestamp_tz as zqu__valid_until,
            zqu__vat_id__c::varchar as zqu__vat_id,
            zqu__zuorasubscriptionid__c::varchar as zqu__zuora_subscription_id,
            zqu__billcycleday__c::varchar as zqu__bill_cycle_day,
            zqu__billingcycleday__c::varchar as zqu__billing_cycle_day,
            zqu__zuoraaccountid__c::varchar as zqu__zuora_account_id,

            -- metadata
            createdbyid::varchar as created_by_id,
            createdbylastname__c::varchar as created_by_lastname,
            createdbyphone__c::varchar as created_by_phone,
            lastmodifiedbyid::varchar as last_modified_by_id,
            lastactivitydate::timestamp_tz as last_activity_date,
            lastmodifieddate::timestamp_tz as last_modified_date,
            lastvieweddate::timestamp_tz as last_viewed_date,
            lastreferenceddate::timestamp_tz as last_referenced_date,
            isdeleted::boolean as is_deleted,
            _sdc_extracted_at::timestamp_tz as sdc_extracted_at,
            _sdc_received_at::timestamp_tz as sdc_received_at,
            _sdc_batched_at::timestamp_tz as sdc_batched_at,
            _sdc_sequence::number as sdc_sequence,
            _sdc_table_version::number as sdc_table_version

        from source
    )

select *
from renamed
