version: 2

models:
  - name: gitlab_ops_labels_xf
    description: This data model contains the data for the label table in the ops.gitlab.net database 
    columns:
      - name: label_id
        tests:
          - not_null
      - name: masked_label_title
        description: '{{ doc("xf_visibility_documentation") }}'

  - name: gitlab_ops_merge_requests_xf
    description: This data model contains the data for the merge_request table in the ops.gitlab.net database 
    columns:
      - name: merge_request_id
      - name: is_community_contributor_related
        description: Merge Request has 'community contribution' tag, and is on a project in the gitlab.org namespace.

  - name: gitlab_ops_projects_xf
    description: This data model contains the data for the project table in the ops.gitlab.net database 
    columns:
      - name: project_id
        tests:
          - not_null
          - unique
      - name: member_count
        description: The number of members that are presently associated with the project.

  - name: gitlab_ops_users_xf
    description: This data model contains the data for the user table in the ops.gitlab.net database 
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: days_active
        description: days between user creation and last activity
      - name: account_age_cohort
        description: cohorting of time between last dbt run and user creation date.    

