version: 2

models:
  - name: gitlab_ops_labels
    description: This data model represents the `labels` table from ops.gitlab.net database. 
  - name: gitlab_ops_merge_requests
    description: This data model represents the `merge_requests` table from ops.gitlab.net database. 
  - name: gitlab_ops_projects
    description: This data model represents the `projects` table from ops.gitlab.net database. 
  - name: gitlab_ops_users
    description: This data model represents the `users` table from ops.gitlab.net database. 
