version: 2

models:
  - name: gitlab_user_outbound
    description: Provides gitlab user data with business emails to zoominfo.
    columns:
      - name: row_integer
      - name: first_name
      - name: last_name
      - name: users_name
      - name: email_id
      - name: internal_value1
      - name: internal_value2
      - name: company_name
      - name: parent_company_name
      - name: email_type
