version: 2

models:
  - name: zi_comp_with_linkages_global
    description: International table, data ingested from Zoominfo inbound share.

  - name: zi_reference_techs
    description: Technograph table, data ingested from Zoominfo inbound share.
  
  - name: gitlab_contact_enhance
    description: User company matched table which appends company information to the user list Gitlab sends to zoominfo. Data ingested from Zoominfo inbound share.