version: 2

models:
  - name: greenhouse_hiring_team
    description: Identifies the team member assigned to greenhouse hiring team roles (recruiter, coordinator, hiring manager, and sourcer) on a job_id level. Note - a job_id can have multiple individuals assigned to a role.
    columns:
      - name: hiring_team.job_id,
      - name: hiring_team_role
      - name: is_responsible
      - name: employee_id
      - name: full_name
      - name: hiring_team_created_at
      - name: hiring_team_updated_at
      
  - name: greenhouse_recruiting_xf
    description: This is shows all applications submitted and ties in offer data, greenhouse department (the associated division), and source data to be in 1 place.
    columns:
        - name: unique_key
          description: Unique key based on application_id, offer_id, candidate_id, requisition_id, and job_id
          tests: 
            - unique
            - not_null
        - name: application_id
        - name: offer_id
        - name: candidate_id
        - name: job_id
        - name: requisition_id
        - name: is_prospect
        - name: application_status
        - name: stage_name
        - name: offer_status
        - name: application_date
          description: The date the candidate applied for a specific job posting.
        - name: offer_sent_date
          description: The date the candidate was sent an offer
        - name:  offer_resolved_date
          description: The date the candidate either accepted or rejected the offer.
        - name: job_name
        - name: department_name
        - name: division
        - name: source_name
          description: Where the candidate came from 
        - name: source_type
        - name: is_outbound
          description: Indicates whether the applicant source is from outbound recruiting. A 1 indicates the applicant came through the outbound recruiting model vs a 0 indicates they did not.
        - name: is_sourced
          description: Indicates whether the candidate was sourced by the recruiting team. A 1 indicates the candidate was sourced, and a 0 indicates they were not.
        - name: sourcer_name
        - name: candidate_recruiter
        - name: candidate_coordinator
        - name: sourced_candidate
          description: Identifies if the source is LinkedIn(Prospecting)
        - name: time_to_offer
          description: Shows how long an applicant to go from applying to accepting an offer. This is based on offer accept month.
        - name: is_hired_in_bamboo
          description: This indicates if the candidate got hired and appears in bamboohr. 
  - name: greenhouse_diversity_intermediate
    description: This is the intermediate model used for greenhouse_diversity. It builds out a base that includes month_date, a column for all the various eeoc_field_names, and joins greenhouse_recruiting_xf to ensure each candidate is tied to an eeoc_field. In the event the candidate did not answer, the response is 'Did not identify'. This is later used in the greenhouse_diversity rpt to aggregate metrics.
    columns:
        - name: month_date
        - name: eeoc_field_name
          description: This column lists the eeoc_fields and ties it to each application. As a result, an applicant will have a response for gender, race, etc if it is null.                  
        - name: capture_month
          description: This identifies if the data is captured for the application month, the offer sent month, or offer_accepted. The metrics associated to these are grouped up in the greenhouse_diversity rpt.
        - name: application_id
        - name: department_name
        - name: division
        - name: division_modified
        - name: source_type
        - name: eeoc_values
          description: This field indicates the diversity for a candidate. For example, tying this to eeoc_field_name = 'Candidate_Gender' we can see the gender of the candidate if they choose to respond.
        - name: accepted_offer
          description: If the offer_status = 'accepted' then this will be a 1, otherwise 0. This is used later to aggregate offers in the greenhouse_diversity model.
        - name: time_to_offer
          description: Shows how long an applicant to go from applying to accepting an offer. This is based on offer accept month. 
        - name: sourced_candidate
          description: Candidates sourced through LinkedIn.
        - name: hired_sourced_candidates        

  - name: greenhouse_opening_custom_fields
    description: Brings in greenhouse custom fields based on job opening. Note - we started capturing this data on a consistent basis starting 2020.05
    columns:
      - name: job_id
      - name: opening_id
      - name: type
        description: Identifies if the field is a backfill or new hire
      - name: hiring_manager
      - name: finance_id
      - name: if_backfill_what_s_the_member_s_name
  

  - name: greenhouse_stage_intermediate
    description: This data model shows all the greenhouse stages a candidate is in, and adds in additional information about the recruiting process such as source type, source name, recruiter, sourcer.
    columns:
        - name: unique_key
        - name: application_id
        - name: candidate_id
        - name: application_stage
        - name: is_milestone_stage
        - name: stage_entered_on
        - name: stage_exited_on
        - name: month_stage_entered_on
        - name: month_stage_exited_on
        - name: days_in_stage
        - name: days_between_stages
        - name: days_in_pipeline
        - name: row_number_stages_desc
        - name: next_stage
        - name: is_current_stage
        - name: application_month
        - name: job_id
        - name: requisition_id
        - name: is_prospect
        - name: current_stage_name
        - name: application_status
        - name: job_name
        - name: department_name
        - name: division_modified
        - name: source_name
        - name: source_type
        - name: is_outbound
        - name: is_source
        - name: sourcer_name
        - name: candidate_recruiter
        - name: candidate_coordinator
        - name: rejection_reason_name
        - name: rejection_reason_type
        - name: current_job_req_status
        - name: is_hired_in_bamboo
        - name: time_to_offer
        - name: hit_application_review
        - name: hit_assessment
        - name: hit_screening
        - name: hit_team_interview
        - name: hit_reference_check
        - name: hit_offer
        - name: hit_hired
        - name: hit_rejected 
        - name: candidate_dropout
        - name: in_current_pipeline
        - name: turn_time_app_review_to_screen
          description: Time in days between when an application was reviewed and screened
        - name: turn_time_screen_to_interview
          description: Time in days between screening and interview_to_hire
        - name: turn_time_interview_to_offer
          description: Time in days between interview and offer

  - name: greenhouse_stage_analysis
    description: Provides the state of all candidates in our recruiting pipeline. This model is used to understand movement through the pipeline, bottlenecks and performance. The fields are the same as greenhouse_stage_intermediate but we have removed application_id and candidate_id and changed dates to month format.

  
  - name: greenhouse_sourcer
    description: This model is used to identify who the sourcer is for candidates. This is specific to source type = 'Prospecting'

  - name: greenhouse_hires
    description: This model is used to identify all greenhouse hires (including transfers within company). We want to capture the date the candidate truly started in bamboohr.
    columns:
      - name: unique_key
        tests:
          - unique
          - not_null
      - name: application_id
      - name: candidate_id
      - name: greenhouse_candidate_row_number
        description: Indiciates the number of applications the candidate submitted and was hired for. For example, a 2 would be their second hire within the company.
      - name: hire_date_mod
        description: Note - this is a calculated field. In the case we don't have the candidate target hire date we are using the first record from the employment status table. If we do then we factor in the time between the candidate target hire and the bamboo hire date, and if it is less than 120 days we use the bamboo hire date, otherwise the target_hire (the reason for this is because we don't have every application record for candidates hired prior to greenhouse. If this is the 2+ hired record in greenhouse we use the candidate target hire date as this candidate is a transfer.
      - name: hire_type
        description: Indicates whether the candidate is a hire, rehire, or transfer based on greenhouse_candidate_row_number.
      - name: job_opening_type
        description: Identifies if job is backfill, new hire, internal transfer, or open to current employees.
      - name: division
      - name: department
        
  - name: greenhouse_sourcer_metrics
    description: This provides recruiting metrics by sourcer and month.
    columns: 
        - name: month_date
        - name: sourcer_name
        - name: part_of_recruiting_team
          description: This uses bamboohr data to identify if the sourcer was on the recruiting team for that month.
        - name: propspected
        - name: prospect_to_review
        - name: prospect_to_screen
        - name: PROSPECT_TO_HIRE
        - name: prospect_to_dropout
        - name: app_reviewed
        - name: review_to_screen
        - name: review_to_hire
        - name: screen
        - name: screen_to_interview
        - name: screen_to_hire
        - name: team_interview
        - name: interview_to_hire
        - name: interview_to_hire
        - name: interview_to_reject
        - name: executive_interview
        - name: exec_interview_to_hire
        - name: reference_check
        - name: candidate_dropout
        - name: offer
        - name: offer_to_hire
        - name: hired
        - name: time_to_offer_median

  - name: greenhouse_sourcer_base
    description: This is the base model used to create out greenhouse_sourcer_scorecard. This creates a rolling 3 month dataset for 3 months prior to the reporting period, which allows us to average out performance metrics.         