version: 2

models:
    - name: airflow_dag
      description: "Static information about airflow DAGs."
      columns:
        - name: dag_id
        - name: is_active
        - name: is_paused
        - name: schedule_interval
        
    - name: airflow_dag_run
      description: "Information about individual runs of a DAG."
      columns:
        - name: dag_id
        - name: execution_date
        - name: run_state
