with
    source as (

        select
            cost_key as cost_key,
            atp_key as atp_key,
            tp_key as tp_key,
            page_view_key as page_view_key,
            session_key as session_key,
            visitor_id as visitor_id,
            cookie_id as cookie_id,
            form_submit_key as form_submit_key,
            impression_key as impression_key,
            current_page_key as current_page_key,
            referrer_page_key as referrer_page_key,
            form_page_key as form_page_key,
            ad_provider_key as ad_provider_key,
            channel_key as channel_key,
            campaign_key as campaign_key,
            keyword_key as keyword_key,
            ad_key as ad_key,
            ad_group_key as ad_group_key,
            creative_key as creative_key,
            site_key as site_key,
            advertiser_key as advertiser_key,
            ad_account_key as ad_account_key,
            placement_key as placement_key,
            category_01_key as category_01_key,
            category_02_key as category_02_key,
            category_03_key as category_03_key,
            category_04_key as category_04_key,
            category_05_key as category_05_key,
            category_06_key as category_06_key,
            category_07_key as category_07_key,
            category_08_key as category_08_key,
            category_09_key as category_09_key,
            category_10_key as category_10_key,
            category_11_key as category_11_key,
            category_12_key as category_12_key,
            category_13_key as category_13_key,
            category_14_key as category_14_key,
            category_15_key as category_15_key,
            type as type,
            date as date,
            timestamp as timestamp,
            modified_date as modified_date,
            cost_in_micro as cost_in_micro,
            impressions as impressions,
            clicks as clicks,
            first_click_percentage as first_click_percentage,
            last_anon_click_percentage as last_anon_click_percentage,
            u_shape_percentage as u_shape_percentage,
            w_shape_percentage as w_shape_percentage,
            full_path_percentage as full_path_percentage,
            custom_model_percentage as custom_model_percentage,
            amount as amount,
            is_won as is_won,
            is_opp_closed as is_opp_closed,
            opportunity_id as opportunity_id,
            opp_created_date as opp_created_date,
            opp_close_date as opp_close_date,
            contact_created_date as contact_created_date,
            contact_id as contact_id,
            email as email,
            lead_created_date as lead_created_date,
            lead_id as lead_id,
            is_aggregatable_cost_ad as is_aggregatable_cost_ad,
            is_aggregatable_cost_advertiser as is_aggregatable_cost_advertiser,
            is_aggregatable_cost_ad_account as is_aggregatable_cost_ad_account,
            is_aggregatable_cost_ad_group as is_aggregatable_cost_ad_group,
            is_aggregatable_cost_campaign as is_aggregatable_cost_campaign,
            is_aggregatable_cost_channel as is_aggregatable_cost_channel,
            is_aggregatable_cost_creative as is_aggregatable_cost_creative,
            is_aggregatable_cost_keyword as is_aggregatable_cost_keyword,
            is_aggregatable_cost_placement as is_aggregatable_cost_placement,
            is_aggregatable_cost_site as is_aggregatable_cost_site,
            is_deleted as is_deleted,
            currency_id as currency_id,
            _created_date as _created_date,
            _modified_date as _modified_date,
            _deleted_date as _deleted_date
        from {{ source("bizible", "biz_facts") }}

    )

select *
from source
