version: 2

models:
  - name: gitlab_dotcom_project_group_links
    description: "gitlab_dotcom_project_group_links"
    columns:
      - name: group_id
        description: External group namespace receiving access to the original project namespace.
      - name: project_id
        description: Original project namespace providing access to the external group namespace.
      - name: group_access
        description: The maximum level of access granted to the external group defined by the originator of the connection. 

  - name: gitlab_dotcom_group_group_links
    description: "gitlab_dotcom_group_group_links"
    columns:
      - name: shared_with_group_id
        description: External group namespace receiving access to the original group namespace.
      - name: shared_group_id
        description: Original group namespace providing access to the external group namespace.
      - name: group_access
        description: The maximum level of access granted to the external group defined by the originator of the connection. 
