name: sqlfmt

on:
  pull_request:

jobs:
  static:
    name: sqlfmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sqlfmt
        run: pip install shandy-sqlfmt[jinjafmt]
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Run sqlfmt
        run: sqlfmt ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Commit sqlfmt changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: sqlfmt"